FROM python:3.11-slim

WORKDIR /app

# ustawiamy Python path, żeby import 'main' działał
ENV PYTHONPATH=/app

# kopiujemy tylko pliki z zależnościami (cache Dockera)
COPY requirements.txt .
COPY requirements-test.txt .

# instalacja zależności
RUN pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

# nie kopiujemy kodu aplikacji
# będzie montowany jako volume

# uruchamiamy testy
CMD ["pytest", "-q", "--tb=short", "--disable-warnings"]
